# Generated by Django 5.0.2 on 2024-03-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_producto_created_producto_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaproductos',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='update',
            new_name='updated',
        ),
    ]
