# Generated by Django 5.0.2 on 2024-03-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0002_alter_servicios_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
